choco install -y googlechrome
choco install -y skype
choco install -y 7zip.install
choco install -y notepadplusplus.install
choco install -y git.install
choco install -y putty.install
choco install -y nodejs.install
choco install -y dotnetcore-sdk
choco install -y vscode
choco install -y yarn
choco install -y paket
choco install -y fake
choco install -y fiddler
choco install -y foxitreader
choco install -y docker
choco install -y slack
choco install -y f.lux.install